### PR TITLE
Mm/working test database

### PR DESCRIPTION
**Pull request by MarchandMD**
# What does this PR do? 
- [x] adds `NODE_ENV` to package.json
- [x] creates `tasks.test.js`
- [x] removes `.cjs` file extension from swaggerdocs file
- [x] runs `npm run build` to update `dist/` directory 

# How does this PR accomplish that? 
- see git diffs

### CODE REVIEW

**Comment by msakr21** [comment]
I viewed it but need to test it out locally before I can review it properly. I should be able to do so when I'm done with work tonight. 

I do have a question for you, @MarchandMD, that I'll be sending on slack!

**Comment by MarchandMD** [comment]
That's cool. I'm not in a rush; I pushed this so you could see the actual code. @msakr21

**Comment by MarchandMD** [comment]
## Additional features: 
- [x] updates `MONGODB_URI` definition to connect to either dev or test db
- [x] writes additional test for `/tasks`

**Comment by MarchandMD** [comment]
added an `afterAll()` method, that'll teardown all the test Tasks

**Comment by MarchandMD** [comment]
updates syntax for exporting/importing defaults

**Comment by msakr21** [comment]
Pushed in an update to be able to remove index.js, as well as change the require app in the test to an import to make tests pass.

**Review by msakr21 — APPROVED** [review]

**Pull request merged**
